trybekkas_kategorier = {
    "Top picks": [
        "The Shawshank Redemption",
        "Oldeuboi",
        "Cidade de Deus",
        "Lost in Translation",
        "Marriage Story",
        "To Kill a Mockingbird",
        "Whiplash",
        "Three Billboards Outside Ebbing, Missouri",
        "Fight Club",
        "Master and Commander: The Far Side of the World",
        "Office Space",
        "Sen to Chihiro no kamikakushi",
        "Superbad",
        "Contact",
        "Into the Wild",
        "Dog Day Afternoon",
        "Mulholland Dr.",
        "Mid90s",
        "Batoru rowaiaru",
        "Kopps",
        "Reservoir Dogs",
        "The Truman Show",
        "The Breakfast Club",
        "Se7en",
        "Pulp Fiction",
        "Once Upon a Time in... Hollywood",
        "The Departed",
    ],
    "Popkulturell referanse": [
        "The Shawshank Redemption",
        "Forrest Gump",
        "The Matrix",
        "Back to the Future",
        "Back to the Future Part II",
        "Pirates of the Caribbean: The Curse of the Black Pearl",
        "Harry Potter and the Sorcerer's Stone",
        "Harry Potter and the Chamber of Secrets",
        "The Lord of the Rings: The Fellowship of the Ring",
        "Star Wars",
        "Casablanca",
        "Inception",
        "Interstellar",
        "Fight Club",
        "Airplane!",
        "Citizen Kane",
        "2001: A Space Odyssey",
        "Die Hard",
        "The Big Lebowski",
        "Requiem for a Dream",
        "Good Will Hunting",
        "The Breakfast Club",
        "The Truman Show",
        "Elling",
        "American Psycho",
        "The Dark Knight",
        "Django Unchained",
        "Inglourious Basterds",
        "Catch Me If You Can",
        "Raiders of the Lost Ark",
        "Apollo 13",
        "Taxi Driver",
        "Gladiator",
        "8 Mile",
        "The Sixth Sense",
        "V for Vendetta",
        "Donnie Darko",
        "Groundhog Day",
        "Jurassic Park",
        "Verdens verste menneske",
        "The Goonies",
    ],
    "Se før du dør": [
        "The Shawshank Redemption",
        "Forrest Gump",
        "Gone with the Wind",
        "Casablanca",
        "To Kill a Mockingbird",
        "Airplane!",
        "Citizen Kane",
        "2001: A Space Odyssey",
        "12 Angry Men",
        "The Godfather",
        "Rear Window",
        "American History X",
        "Pulp Fiction",
        "Elling",
        "Mulholland Dr.",
        "Nuovo Cinema Paradiso",
        "Butch Cassidy and the Sundance Kid",
        "Apocalypse Now",
        "One Flew Over the Cuckoo's Nest",
        "Lawrence of Arabia",
        "Reservoir Dogs",
        "Requiem for a Dream",
        "Casino",
        "Once Upon a Time in America",
        "Psycho",
        "The Departed",
        "There Will Be Blood",
        "Donnie Brasco",
        "Taxi Driver",
        "Persona",
        "Cast Away",
        "Gladiator",
        "Fargo",
        "The Shining",
        "Harry Potter and the Sorcerer's Stone",
        "The Lord of the Rings: The Fellowship of the Ring",
        "Star Wars",
        "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
        "No Country for Old Men",
        "Blade Runner",
        "GoodFellas",
        "The Silence of the Lambs",
        "The Usual Suspects",
        "Se7en",
    ],
    "Gråtefilm": [
        "The Shawshank Redemption",
        "Forrest Gump",
        "Marriage Story",
        "The Pursuit of Happyness",
        "To Kill a Mockingbird",
        "West Side Story",
        "In the Heights",
        "Hotaru no haka",
        "Gladiator",
        "Intouchables",
        "Verdens verste menneske",
        "La vita è bella",
    ],
    "Familiekveld": [
        "Master and Commander: The Far Side of the World",
        "The Shawshank Redemption",
        "Forrest Gump",
        "Back to the Future",
        "Back to the Future Part II",
        "Police Academy",
        "Coming to America",
        "Airplane!",
        "Becoming Bond",
        "The Hunt for Red October",
        "Super 8",
        "Into the Wild",
        "Good Will Hunting",
        "The Man from U.N.C.L.E.",
        "Stand by Me",
        "Kingsman: The Secret Service",
        "First Man",
        "Raiders of the Lost Ark",
        "Dune: Part One",
        "Apollo 13",
        "You Only Live Twice",
        "Pirates of the Caribbean: The Curse of the Black Pearl",
        "Harry Potter and the Sorcerer's Stone",
        "Harry Potter and the Chamber of Secrets",
        "The Lord of the Rings: The Fellowship of the Ring",
        "Star Wars",
        "Contact",
        "Blade Runner",
        "Snatch",
        "The Usual Suspects",
        "Se7en",
        "Jurassic Park",
        "October Sky",
    ],
    "Tenkefilm": [
        "Inception",
        "Interstellar",
        "Memento",
        "Oldeuboi",
        "Ex Machina",
        "Shutter Island",
        "Tenet",
        "Persona",
        "Donnie Darko",
        "Being John Malkovich",
    ],
    "Ikke-tenkefilm": [
        "Superbad",
        "Office Space",
        "The Big Lebowski",
        "Clerks",
        "Clueless",
        "Licorice Pizza",
    ],
    "Morsomt": [
        "Superbad",
        "Office Space",
        "Airplane!",
        "Kopps",
        "Nine to Five",
        "Hot Fuzz",
        "A Futile and Stupid Gesture",
        "Kick-Ass",
        "21 Jump Street",
        "Anchorman: The Legend of Ron Burgundy",
        "Step Brothers",
        "The Invention of Lying",
        "Mænd & høns",
        "Life of Brian",
        "This Is Spinal Tap",
        "Caddyshack",
    ],
    "Dokumentarer": [
        "Senna",
        "Jiro Dreams of Sushi",
        "Becoming Bond",
        "Icarus",
        "Won't You Be My Neighbor?",
        "Canada på tvers med Lars Monsen",
        "Dear Zachary: A Letter to a Son About His Father",
        "Free Solo",
        "American Movie",
        "Indie Game: The Movie",
        "Sour Grapes",
        "Exit Through the Gift Shop",
        "The King of Kong",
        "Hands on a Hard Body: The Documentary",
        "Jodorowsky's Dune",
        "They Shall Not Grow Old",
        "This Is Spinal Tap",
        "Bones Brigade: An Autobiography",
    ],
    "KRIG!": [
        "Apocalypse Now",
        "Dunkirk",
        "Letters from Iwo Jima",
        "Saving Private Ryan",
        "The Hunt for Red October",
        "1917",
        "Hacksaw Ridge",
        "La vita è bella",
        "The Pianist",
        "The Bridge on the River Kwai",
        "Empire of the Sun",
    ],
    "Julefilm": [
        "Home Alone",
        "Home Alone 2: Lost in New York",
        "Star Wars",
        "Pirates of the Caribbean: The Curse of the Black Pearl",
        "Harry Potter and the Sorcerer's Stone",
        "Harry Potter and the Chamber of Secrets",
        "The Lord of the Rings: The Fellowship of the Ring",
        "Police Academy",
        "National Lampoon's Vacation",
        "National Lampoon's Christmas Vacation",
        "Die Hard",
        "Die Hard 2",
        "Die Hard with a Vengeance",
        "Blade Runner",
    ],
    "Animasjon": [
        "Sen to Chihiro no kamikakushi",
        "Toy Story 3",
        "Isle of Dogs",
        "Flåklypa Grand Prix",
        "Ratatouille",
        "WALL·E",
    ],
    "Musikal": [
        "La La Land",
        "Moulin Rouge!",
        "Les Misérables",
        "Once",
        "In the Heights",
        "West Side Story",
        "The Sound of Music",
    ],
    "Barnefilm": [
        "Sen to Chihiro no kamikakushi",
        "Toy Story 3",
        "Flåklypa Grand Prix",
        "WALL·E",
        "The Lion King",
        "The Goonies",
        "Flubber",
        "Hook",
        "Die unendliche Geschichte",
        "Harry Potter and the Sorcerer's Stone",
        "Harry Potter and the Chamber of Secrets",
        "Star Wars",
        "Back to the Future",
        "Back to the Future Part II",
    ],
    "Ukategorisert Bra": [
        "Room",
        "Manchester by the Sea",
        "The Hateful Eight",
        "Nightcrawler",
        "Gran Torino",
        "Jagten",
        "American Beauty",
        "Equilibrium",
        "Adventureland",
        "Her",
        "Lords of Dogtown",
    ],
}
